const comentarios=({produto,empresa})=>{
const comentarios = {
  celular: [
    {
      id: 1,
      nome: "Ana Souza",
      email: "ana.souza@email.com",
      comentario: `Comprei na ${empresa} e chegou tudo certo! Produto excelente.`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Bruno Lima",
      email: "bruno.lima@email.com",
      comentario: `A experiência com ${empresa} foi boa, mas a entrega demorou um pouco.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Carla Mendes",
      email: "carla.mendes@email.com",
      comentario: `Produto da ${empresa} chegou rápido, mas veio com pequenos defeitos.`,
      estrelas: 2,
    },
    {
      id: 4,
      nome: "Diego Santos",
      email: "diego.santos@email.com",
      comentario: `Smartphone da ${empresa} superou expectativas! Bateria dura o dia todo.`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Eliana Costa",
      email: "eliana.costa@email.com",
      comentario: `Celular bom da ${empresa}, mas a câmera poderia ser melhor pelo preço.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Fernando Rocha",
      email: "fernando.rocha@email.com",
      comentario: `Comprei na ${empresa} e o aparelho veio travando, muito decepcionante.`,
      estrelas: 1,
    },
  ],

  tecnologia: [
    {
      id: 1,
      nome: "Daniel Oliveira",
      email: "daniel.oliveira@email.com",
      comentario: `Muito satisfeito com a compra na ${empresa}, tudo certo!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Eduarda Ferreira",
      email: "eduarda.ferreira@email.com",
      comentario: `Entrega da ${empresa} foi lenta, mas o produto é bom.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Gabriel Torres",
      email: "gabriel.torres@email.com",
      comentario: `Notebook da ${empresa} roda todos os programas perfeitamente, recomendo!`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Helena Martins",
      email: "helena.martins@email.com",
      comentario: `Mouse gamer da ${empresa} bom, mas o cabo é meio curto.`,
      estrelas: 4,
    },
    {
      id: 5,
      nome: "Ivan Moreira",
      email: "ivan.moreira@email.com",
      comentario: `SSD da ${empresa} aumentou muito a velocidade do meu PC!`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Joana Silva",
      email: "joana.silva@email.com",
      comentario: `Cabo USB da ${empresa} parou de funcionar em uma semana.`,
      estrelas: 2,
    },
  ],

  eletrodomesticos: [
    {
      id: 1,
      nome: "Felipe Castro",
      email: "felipe.castro@email.com",
      comentario: `Compra na ${empresa} incrível, recomendo para todos!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Gabriela Rocha",
      email: "gabriela.rocha@email.com",
      comentario: `Produto da ${empresa} de boa qualidade, mas o atendimento poderia melhorar.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Henrique Lima",
      email: "henrique.lima@email.com",
      comentario: `Geladeira da ${empresa} chegou com amassado, mas funciona bem.`,
      estrelas: 3,
    },
    {
      id: 4,
      nome: "Iara Santos",
      email: "iara.santos@email.com",
      comentario: `Microondas da ${empresa} esquenta super rápido, estou amando!`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "João Carlos",
      email: "joao.carlos@email.com",
      comentario: `Máquina de lavar da ${empresa} é silenciosa e lava muito bem.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Kelly Alves",
      email: "kelly.alves@email.com",
      comentario: `Liquidificador da ${empresa} quebrou no terceiro uso, péssimo!`,
      estrelas: 1,
    },
  ],

  moda: [
    {
      id: 1,
      nome: "Hugo Martins",
      email: "hugo.martins@email.com",
      comentario: `Adorei as roupas da ${empresa}, mas algumas vieram do tamanho errado.`,
      estrelas: 3,
    },
    {
      id: 2,
      nome: "Isabela Costa",
      email: "isabela.costa@email.com",
      comentario: `A entrega da ${empresa} demorou, mas a qualidade é excelente!`,
      estrelas: 4,
    },
    {
      id: 3,
      nome: "Leonardo Pires",
      email: "leonardo.pires@email.com",
      comentario: `Calça jeans da ${empresa} tem ótimo caimento e preço justo.`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Monica Dias",
      email: "monica.dias@email.com",
      comentario: `Vestido da ${empresa} lindo, mas o tecido é bem fininho.`,
      estrelas: 3,
    },
    {
      id: 5,
      nome: "Nicolas Campos",
      email: "nicolas.campos@email.com",
      comentario: `Tênis da ${empresa} super confortável, uso para trabalhar.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Olivia Ramos",
      email: "olivia.ramos@email.com",
      comentario: `Bolsa da ${empresa} rasgou na primeira semana, muito ruim.`,
      estrelas: 1,
    },
  ],

  alimentacao: [
    {
      id: 1,
      nome: "João Pedro",
      email: "joao.pedro@email.com",
      comentario: `O pedido chegou rápido da ${empresa}, mas alguns itens estavam com validade próxima.`,
      estrelas: 3,
    },
    {
      id: 2,
      nome: "Karen Lima",
      email: "karen.lima@email.com",
      comentario: `Muito contente com a compra na ${empresa}, produtos frescos e saborosos!`,
      estrelas: 5,
    },
    {
      id: 3,
      nome: "Luciano Costa",
      email: "luciano.costa@email.com",
      comentario: `Frutas da ${empresa} chegaram maduras no ponto, perfeitas!`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Marcia Alves",
      email: "marcia.alves@email.com",
      comentario: `Cereais da ${empresa} bons, mas a embalagem veio amassada.`,
      estrelas: 3,
    },
    {
      id: 5,
      nome: "Nelson Santos",
      email: "nelson.santos@email.com",
      comentario: `Carnes da ${empresa} de excelente qualidade, sempre compro aqui.`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Paula Ribeiro",
      email: "paula.ribeiro@email.com",
      comentario: `Legumes da ${empresa} estragaram rapidamente, não recomendo.`,
      estrelas: 2,
    },
  ],

  livros: [
    {
      id: 1,
      nome: "Lucas Almeida",
      email: "lucas.almeida@email.com",
      comentario: `Livro da ${empresa} chegou rasgado, fiquei decepcionado.`,
      estrelas: 1,
    },
    {
      id: 2,
      nome: "Mariana Santos",
      email: "mariana.santos@email.com",
      comentario: `Entrega rápida da ${empresa}, livros em ótimo estado, recomendo!`,
      estrelas: 5,
    },
    {
      id: 3,
      nome: "Octavio Luz",
      email: "octavio.luz@email.com",
      comentario: `Livros técnicos da ${empresa} são atualizados e bem explicados.`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "Priscila Moura",
      email: "priscila.moura@email.com",
      comentario: `Romance da ${empresa} chegou rápido, história envolvente!`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Renato Silva",
      email: "renato.silva@email.com",
      comentario: `Quadrinhos da ${empresa} com boa qualidade de papel e impressão.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Sandra Torres",
      email: "sandra.torres@email.com",
      comentario: `Livro infantil da ${empresa} veio com páginas soltas.`,
      estrelas: 2,
    },
  ],

  saude_beleza: [
    {
      id: 1,
      nome: "Natália Silva",
      email: "natalia.silva@email.com",
      comentario: `Produtos de skincare da ${empresa} são ótimos, minha pele melhorou muito!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Otavio Reis",
      email: "otavio.reis@email.com",
      comentario: `Comprei suplementos na ${empresa}, mas a embalagem estava danificada.`,
      estrelas: 2,
    },
    {
      id: 3,
      nome: "Patricia Nunes",
      email: "patricia.nunes@email.com",
      comentario: `Perfumes da ${empresa} com preços justos e entrega rápida.`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "Rodrigo Campos",
      email: "rodrigo.campos@email.com",
      comentario: `Shampoo da ${empresa} deixou meu cabelo muito macio e brilhante.`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Simone Freitas",
      email: "simone.freitas@email.com",
      comentario: `Base da ${empresa} tem boa cobertura, mas oxidou na minha pele.`,
      estrelas: 3,
    },
    {
      id: 6,
      nome: "Tiago Barbosa",
      email: "tiago.barbosa@email.com",
      comentario: `Proteína da ${empresa} tem gosto ruim, não consegui tomar.`,
      estrelas: 2,
    },
    {
      id: 7,
      nome: "Vanessa Correia",
      email: "vanessa.correia@email.com",
      comentario: `Hidratante da ${empresa} é maravilhoso, deixa a pele sedosa.`,
      estrelas: 5,
    },
  ],

  games: [
    {
      id: 1,
      nome: "Ricardo Barbosa",
      email: "ricardo.barbosa@email.com",
      comentario: `Console chegou perfeito da ${empresa}, super recomendo para gamers!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Sofia Torres",
      email: "sofia.torres@email.com",
      comentario: `Jogo veio com defeito da ${empresa}, mas o suporte resolveu rapidamente.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Thomás Mendes",
      email: "thomas.mendes@email.com",
      comentario: `Controle da ${empresa} muito responsivo, melhorou meu desempenho!`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Valentina Cruz",
      email: "valentina.cruz@email.com",
      comentario: `Headset gamer da ${empresa} com áudio incrível, mas é pesado.`,
      estrelas: 4,
    },
    {
      id: 5,
      nome: "Wagner Oliveira",
      email: "wagner.oliveira@email.com",
      comentario: `Jogo indie da ${empresa} é viciante, joguei a noite toda!`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Yadira Santos",
      email: "yadira.santos@email.com",
      comentario: `Cabo HDMI da ${empresa} parou de funcionar em poucos dias.`,
      estrelas: 1,
    },
  ],

  casa_jardim: [
    {
      id: 1,
      nome: "Thiago Moura",
      email: "thiago.moura@email.com",
      comentario: `Móveis da ${empresa} com ótima qualidade, chegaram bem embalados.`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Ursula Campos",
      email: "ursula.campos@email.com",
      comentario: `Plantas da ${empresa} vieram bonitas, mas algumas folhas estavam amareladas.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Vinicius Luz",
      email: "vinicius.luz@email.com",
      comentario: `Ferramentas da ${empresa} são resistentes, mas o preço é um pouco alto.`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "Amanda Silva",
      email: "amanda.silva@email.com",
      comentario: `Sofá da ${empresa} muito confortável, família toda aprovou!`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Bruno Cardoso",
      email: "bruno.cardoso@email.com",
      comentario: `Sementes da ${empresa} germinaram todas, jardim ficou lindo.`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Camila Rocha",
      email: "camila.rocha@email.com",
      comentario: `Mesa da ${empresa} veio riscada, mas a madeira é de qualidade.`,
      estrelas: 3,
    },
    {
      id: 7,
      nome: "Eduardo Pinto",
      email: "eduardo.pinto@email.com",
      comentario: `Furadeira da ${empresa} tem boa potência, recomendo para reformas.`,
      estrelas: 4,
    },
  ],

  pet_shop: [
    {
      id: 1,
      nome: "Wesley Cunha",
      email: "wesley.cunha@email.com",
      comentario: `Ração para meu cachorro da ${empresa} é excelente, ele adorou!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Ximena Araujo",
      email: "ximena.araujo@email.com",
      comentario: `Brinquedos para gatos da ${empresa} são de boa qualidade, mas um veio quebrado.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Fabiana Costa",
      email: "fabiana.costa@email.com",
      comentario: `Coleira da ${empresa} é resistente e meu cachorro não conseguiu quebrar.`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Gustavo Ramos",
      email: "gustavo.ramos@email.com",
      comentario: `Areia para gatos da ${empresa} controla bem o odor, muito boa.`,
      estrelas: 4,
    },
    {
      id: 5,
      nome: "Helena Dias",
      email: "helena.dias@email.com",
      comentario: `Remédio para vermes da ${empresa} funcionou perfeitamente no meu pet.`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Igor Pereira",
      email: "igor.pereira@email.com",
      comentario: `Cama para cachorro da ${empresa} desenformou rapidamente.`,
      estrelas: 2,
    },
  ],

  esportes: [
    {
      id: 1,
      nome: "Yago Pereira",
      email: "yago.pereira@email.com",
      comentario: `Equipamentos de academia da ${empresa} são top, muito satisfeito!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Zara Monteiro",
      email: "zara.monteiro@email.com",
      comentario: `Tênis de corrida da ${empresa} confortável, mas demorou para chegar.`,
      estrelas: 4,
    },
    {
      id: 3,
      nome: "Arthur Gomes",
      email: "arthur.gomes@email.com",
      comentario: `Bicicleta da ${empresa} veio com peças faltando, decepcionante.`,
      estrelas: 1,
    },
    {
      id: 4,
      nome: "Bianca Santos",
      email: "bianca.santos@email.com",
      comentario: `Tapete de yoga da ${empresa} tem ótima aderência, não escorrega.`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Carlos Mendes",
      email: "carlos.mendes@email.com",
      comentario: `Halteres da ${empresa} são pesados e bem balanceados.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Diana Lima",
      email: "diana.lima@email.com",
      comentario: `Bola de pilates da ${empresa} murchou em poucas semanas.`,
      estrelas: 2,
    },
    {
      id: 7,
      nome: "Erick Torres",
      email: "erick.torres@email.com",
      comentario: `Suplemento pré-treino da ${empresa} dá boa energia, recomendo.`,
      estrelas: 4,
    },
  ],

  automotivo: [
    {
      id: 1,
      nome: "Beatriz Cardoso",
      email: "beatriz.cardoso@email.com",
      comentario: `Peças do carro da ${empresa} de qualidade, instalação foi fácil.`,
      estrelas: 4,
    },
    {
      id: 2,
      nome: "Caio Fernandes",
      email: "caio.fernandes@email.com",
      comentario: `Óleo de motor da ${empresa} é bom, mas o preço subiu muito.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Daniela Moreira",
      email: "daniela.moreira@email.com",
      comentario: `Pneus da ${empresa} têm ótima aderência, dirigir ficou mais seguro.`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Evandro Silva",
      email: "evandro.silva@email.com",
      comentario: `Bateria da ${empresa} durou muito menos que o esperado.`,
      estrelas: 2,
    },
    {
      id: 5,
      nome: "Fernanda Cruz",
      email: "fernanda.cruz@email.com",
      comentario: `Kit de som da ${empresa} transformou meu carro, som cristalino!`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Guilherme Alves",
      email: "guilherme.alves@email.com",
      comentario: `Filtro de ar da ${empresa} melhorou o desempenho do motor.`,
      estrelas: 4,
    },
  ],

  instrumentos_musicais: [
    {
      id: 1,
      nome: "Débora Macedo",
      email: "debora.macedo@email.com",
      comentario: `Violão da ${empresa} tem um som incrível, vale cada centavo!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Emilio Ribeiro",
      email: "emilio.ribeiro@email.com",
      comentario: `Teclado da ${empresa} bom para iniciantes, mas algumas teclas grudam.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Flavia Campos",
      email: "flavia.campos@email.com",
      comentario: `Bateria da ${empresa} chegou completa, som potente e afinação perfeita.`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Gabriel Pereira",
      email: "gabriel.pereira@email.com",
      comentario: `Baixo da ${empresa} tem timbre incrível, grave bem definido.`,
      estrelas: 4,
    },
    {
      id: 5,
      nome: "Helena Sousa",
      email: "helena.sousa@email.com",
      comentario: `Microfone da ${empresa} capta muito bem, mas o cabo é curto.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Ivan Costa",
      email: "ivan.costa@email.com",
      comentario: `Flauta da ${empresa} desafinou rapidamente, material barato.`,
      estrelas: 2,
    },
  ],

  bebes_criancas: [
    {
      id: 1,
      nome: "Fernanda Lopes",
      email: "fernanda.lopes@email.com",
      comentario: `Carrinho de bebê da ${empresa} é prático e resistente, adorei!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Gustavo Dias",
      email: "gustavo.dias@email.com",
      comentario: `Brinquedos educativos da ${empresa} são ótimos, mas alguns vieram sujos.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Helena Prado",
      email: "helena.prado@email.com",
      comentario: `Fraldas da ${empresa} absorvem bem, mas o preço poderia ser melhor.`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "João Batista",
      email: "joao.batista@email.com",
      comentario: `Cadeirinha para carro da ${empresa} é segura e bem acolchoada.`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Karina Santos",
      email: "karina.santos@email.com",
      comentario: `Mamadeiras da ${empresa} são fáceis de limpar e não vazam.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Leonardo Cruz",
      email: "leonardo.cruz@email.com",
      comentario: `Roupinhas de bebê da ${empresa} encolheram na primeira lavagem.`,
      estrelas: 2,
    },
    {
      id: 7,
      nome: "Marina Oliveira",
      email: "marina.oliveira@email.com",
      comentario: `Berço da ${empresa} é lindo e muito seguro, recomendo!`,
      estrelas: 5,
    },
  ],

  papelaria: [
    {
      id: 1,
      nome: "Igor Santos",
      email: "igor.santos@email.com",
      comentario: `Material escolar da ${empresa} de ótima qualidade, meus filhos aprovaram!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Julia Ramos",
      email: "julia.ramos@email.com",
      comentario: `Cadernos da ${empresa} são bonitos, mas algumas folhas saíram soltas.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Kevin Torres",
      email: "kevin.torres@email.com",
      comentario: `Canetas da ${empresa} escrevem muito bem, tinta não borra.`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "Leticia Moura",
      email: "leticia.moura@email.com",
      comentario: `Impressora da ${empresa} imprime com qualidade, mas é barulhenta.`,
      estrelas: 3,
    },
    {
      id: 5,
      nome: "Marcelo Silva",
      email: "marcelo.silva@email.com",
      comentario: `Papel sulfite da ${empresa} é de primeira, não emperra na impressora.`,
      estrelas: 5,
    },
    {
      id: 6,
      nome: "Nicole Alves",
      email: "nicole.alves@email.com",
      comentario: `Lápis de cor da ${empresa} perderam a ponta rapidamente.`,
      estrelas: 2,
    },
  ],


  saas: [
    {
      id: 1,
      nome: "André Oliveira",
      email: "andre.oliveira@email.com",
      comentario: `Plataforma da ${empresa} é muito intuitiva, facilitou nossos processos!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Beatriz Melo",
      email: "beatriz.melo@email.com",
      comentario: `Sistema da ${empresa} é bom, mas o suporte técnico demora a responder.`,
      estrelas: 3,
    },
    {
      id: 3,
      nome: "Carlos Eduardo",
      email: "carlos.eduardo@email.com",
      comentario: `Software da ${empresa} aumentou nossa produtividade em 40%!`,
      estrelas: 5,
    },
    {
      id: 4,
      nome: "Daniela Fonseca",
      email: "daniela.fonseca@email.com",
      comentario: `Interface da ${empresa} é confusa, mas as funcionalidades são úteis.`,
      estrelas: 3,
    },
    {
      id: 5,
      nome: "Eduardo Martins",
      email: "eduardo.martins@email.com",
      comentario: `Integração da ${empresa} com outras ferramentas funciona perfeitamente.`,
      estrelas: 4,
    },
    {
      id: 6,
      nome: "Fernanda Pires",
      email: "fernanda.pires@email.com",
      comentario: `Sistema da ${empresa} apresenta muitos bugs, experiência frustrante.`,
      estrelas: 1,
    },
    {
      id: 7,
      nome: "Gabriel Azevedo",
      email: "gabriel.azevedo@email.com",
      comentario: `Relatórios da ${empresa} são completos e ajudam na tomada de decisão.`,
      estrelas: 5,
    },
  ],

  decoracao: [
    {
      id: 1,
      nome: "Kevin Silva",
      email: "kevin.silva@email.com",
      comentario: `Quadros da ${empresa} são lindos e chegaram bem protegidos!`,
      estrelas: 5,
    },
    {
      id: 2,
      nome: "Larissa Freitas",
      email: "larissa.freitas@email.com",
      comentario: `Vasos decorativos da ${empresa} são bonitos, mas um chegou rachado.`,
      estrelas: 2,
    },
    {
      id: 3,
      nome: "Mateus Correia",
      email: "mateus.correia@email.com",
      comentario: `Luminárias da ${empresa} dão um charme especial na sala, recomendo!`,
      estrelas: 4,
    },
    {
      id: 4,
      nome: "Natasha Costa",
      email: "natasha.costa@email.com",
      comentario: `Almofadas da ${empresa} são macias e combinaram perfeitamente com o sofá.`,
      estrelas: 5,
    },
    {
      id: 5,
      nome: "Orlando Santos",
      email: "orlando.santos@email.com",
      comentario: `Cortina da ${empresa} tem tecido de qualidade, mas a cor desbotou.`,
      estrelas: 3,
    },
    {
      id: 6,
      nome: "Pamela Lima",
      email: "pamela.lima@email.com",
      comentario: `Espelho da ${empresa} ficou perfeito no quarto, moldura elegante.`,
      estrelas: 4,
    },
    {
      id: 7,
      nome: "Roberto Machado",
      email: "roberto.machado@email.com",
      comentario: `Tapete da ${empresa} desenformou após poucas semanas.`,
      estrelas: 2,
    },
    {
      id: 8,
      nome: "Stephanie Reis",
      email: "stephanie.reis@email.com",
      comentario: `Velas aromáticas da ${empresa} têm fragrância duradoura, ambiente fica aconchegante.`,
      estrelas: 5,
    },
  ],
};



return comentarios[produto]

}

module.exports = comentarios